rule update_example_data:
    """This updates the files under example_data/ based on latest available data from data.nextstrain.org.

    The subset of data is generated by an augur filter call which:
    - sets the subsampling size to 50
    - samples evenly across time
    - adds everything in defaults/all-lineages/include.txt
    """
    input:
        sequences="results/sequences.fasta",
        metadata="results/metadata.tsv",
    output:
        sequences="example_data/sequences.fasta",
        metadata="example_data/metadata.tsv",
    params:
        strain_id=config["strain_id_field"],
    shell:
        r"""
        augur filter \
            --metadata {input.metadata} \
            --metadata-id-columns {params.strain_id} \
            --sequences {input.sequences} \
            --subsample-max-sequences 50 \
            --group-by month \
            --subsample-seed 0 \
            --include defaults/all-lineages/include.txt \
            --output-metadata {output.metadata} \
            --output-sequences {output.sequences}
        """
