version: 0.2

# Environment variables for modular configuration
env:
  variables:
    # Non-sensitive defaults (can be overridden)
    BATCH_CPUS: "8"
    BATCH_MEMORY: "10240"
    BUILD_TARGET: "phylogenetic"
    BUILD_NAME: "West Nile Virus"
    BUILD_ABBREVIATION: "WNV"
    CONFIG_FILES: "build-configs/nextstrain-automation/config.yaml build-configs/washington-state/config.yaml"
    USE_CONFIG_FILES: "true"
    LOG_LEVEL: "INFO"

    # SECURITY: The following variables MUST be set in CodeBuild Environment Variables
    # - BATCH_QUEUE (required)
    # - BATCH_JOB_DEFINITION (required)
    # - S3_BUCKET (required)

phases:
  pre_build:
    commands:
      # Validate required environment variables
      - echo "🔍 Validating required environment variables..."
      - |
        MISSING_VARS=""
        if [ -z "${BATCH_QUEUE}" ]; then
          MISSING_VARS="${MISSING_VARS} BATCH_QUEUE"
        fi
        if [ -z "${BATCH_JOB_DEFINITION}" ]; then
          MISSING_VARS="${MISSING_VARS} BATCH_JOB_DEFINITION"
        fi
        if [ -z "${S3_BUCKET}" ]; then
          MISSING_VARS="${MISSING_VARS} S3_BUCKET"
        fi

        if [ -n "${MISSING_VARS}" ]; then
          echo "❌ ERROR: Missing required environment variables:${MISSING_VARS}"
          echo "Please set these in your CodeBuild project environment variables:"
          echo "  - BATCH_QUEUE: Your AWS Batch queue name"
          echo "  - BATCH_JOB_DEFINITION: Your AWS Batch job definition name"
          echo "  - S3_BUCKET: Your S3 bucket for Nextstrain jobs"
          exit 1
        fi

        echo "✅ All required environment variables are set"

  build:
    commands:
      - echo "Starting ${BUILD_NAME} Nextstrain build..."
      - echo "Configuration:"
      - echo "  CPUs: ${BATCH_CPUS}"
      - echo "  Memory: ${BATCH_MEMORY} MB"
      - echo "  Queue: ${BATCH_QUEUE}"
      - echo "  Job Definition: ${BATCH_JOB_DEFINITION}"
      - echo "  S3 Bucket: ${S3_BUCKET}"
      - echo "  Build Target: ${BUILD_TARGET}"
      - echo "  Config Files: ${CONFIG_FILES}"
      - echo "  Use Config Files: ${USE_CONFIG_FILES}"

      # Repository is already cloned by CodeBuild
      - echo "Repository already cloned by CodeBuild. Current contents:"
      - pwd
      - ls -la

      # Submit build to AWS Batch with environment variables
      - echo "Submitting ${BUILD_ABBREVIATION} build to AWS Batch..."
      - |
        # Build the nextstrain command dynamically
        NEXTSTRAIN_CMD="nextstrain build"
        NEXTSTRAIN_CMD="${NEXTSTRAIN_CMD} --aws-batch"
        NEXTSTRAIN_CMD="${NEXTSTRAIN_CMD} --detach"
        NEXTSTRAIN_CMD="${NEXTSTRAIN_CMD} --aws-batch-cpus ${BATCH_CPUS}"
        NEXTSTRAIN_CMD="${NEXTSTRAIN_CMD} --aws-batch-memory ${BATCH_MEMORY}"
        NEXTSTRAIN_CMD="${NEXTSTRAIN_CMD} --aws-batch-queue ${BATCH_QUEUE}"
        NEXTSTRAIN_CMD="${NEXTSTRAIN_CMD} --aws-batch-job ${BATCH_JOB_DEFINITION}"
        NEXTSTRAIN_CMD="${NEXTSTRAIN_CMD} --aws-batch-s3-bucket ${S3_BUCKET}"
        NEXTSTRAIN_CMD="${NEXTSTRAIN_CMD} ${BUILD_TARGET}"

        # Add config files only if USE_CONFIG_FILES is true and CONFIG_FILES is not empty
        if [ "${USE_CONFIG_FILES}" = "true" ] && [ -n "${CONFIG_FILES}" ]; then
          NEXTSTRAIN_CMD="${NEXTSTRAIN_CMD} --configfile ${CONFIG_FILES}"
          echo "Using config files: ${CONFIG_FILES}"
        else
          echo "No config files specified or USE_CONFIG_FILES is false"
        fi

        # Execute the command
        echo "Executing: ${NEXTSTRAIN_CMD}"
        eval ${NEXTSTRAIN_CMD}

      - echo "✅ ${BUILD_ABBREVIATION} build submitted successfully to AWS Batch!"
      - echo "Build submission completed. Check AWS Batch console for job progress."
      - echo "Monitor at: https://console.aws.amazon.com/batch/v2/home#queues/detail/${BATCH_QUEUE}"
